# Generated by Django 4.2.2 on 2023-08-05 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmam', '0002_siteintervention_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteintervention',
            name='adresse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='siteintervention',
            name='qrcode',
            field=models.ImageField(blank=True, upload_to='qrcodes/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='siteintervention',
            name='ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='approbateur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Approbateur'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='changementParent',
            field=models.CharField(blank=True, max_length=100, verbose_name='Changement parent'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='client',
            field=models.CharField(blank=True, max_length=100, verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dateAssignation',
            field=models.DateField(blank=True, verbose_name="Date d'assignation"),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dateDebut',
            field=models.DateField(blank=True, verbose_name='Date de debut'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='demandeur',
            field=models.CharField(blank=True, max_length=100, verbose_name='Demandeur'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='dureeDeResolution',
            field=models.CharField(blank=True, max_length=100, verbose_name='Duree de resolution'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='echeanceTTR',
            field=models.DateField(blank=True, verbose_name='Echeance TTR'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='equipe',
            field=models.CharField(blank=True, max_length=100, verbose_name='Equipe'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='etat',
            field=models.CharField(blank=True, max_length=100, verbose_name='Etat'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='impact',
            field=models.CharField(blank=True, max_length=100, verbose_name='Impact'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='origine',
            field=models.CharField(blank=True, max_length=100, verbose_name='Origine'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priorite',
            field=models.CharField(blank=True, max_length=100, verbose_name='Priorite'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='raisonDeSurveillance',
            field=models.CharField(blank=True, max_length=100, verbose_name='Raison de surveillance'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='requeteParente',
            field=models.CharField(blank=True, max_length=100, verbose_name='Requete parente'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='service',
            field=models.CharField(blank=True, max_length=100, verbose_name='Service'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketmam.siteintervention', verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sousCategorieService',
            field=models.CharField(blank=True, max_length=100, verbose_name='Sous categorie de service'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticketASurveiller',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ticket a surveiller'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='titre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='typeDeRequete',
            field=models.CharField(blank=True, max_length=100, verbose_name='Type de requete'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='urgence',
            field=models.CharField(blank=True, max_length=100, verbose_name='Urgence'),
        ),
    ]
