# Generated by Django 4.2.2 on 2023-08-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmam', '0003_alter_siteintervention_adresse_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='site',
        ),
    ]
