# Generated by Django 4.2.2 on 2023-08-07 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ticketmam', '0005_alter_agent_groups_alter_agent_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='agent',
        ),
        migrations.AlterField(
            model_name='agent',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='agents_groups', related_query_name='agent', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='agents_user_permissions', related_query_name='agent', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
