# Generated by Django 4.2.2 on 2023-08-07 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmam', '0006_remove_ticket_agent_alter_agent_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agent'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='site_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketmam.siteintervention', verbose_name='Site'),
        ),
    ]
