# Generated by Django 4.2.2 on 2023-08-07 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmam', '0007_ticket_agent_ticket_site_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
