# Generated by Django 4.2.2 on 2023-08-07 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmam', '0008_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(blank=True, max_length=100, verbose_name='Client')),
                ('demandeur', models.CharField(blank=True, max_length=100, verbose_name='Demandeur')),
                ('etat', models.CharField(blank=True, max_length=100, verbose_name='Etat')),
                ('origine', models.CharField(blank=True, max_length=100, verbose_name='Origine')),
                ('titre', models.CharField(blank=True, max_length=100, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('service', models.CharField(blank=True, max_length=100, verbose_name='Service')),
                ('sousCategorieService', models.CharField(blank=True, max_length=100, verbose_name='Sous categorie de service')),
                ('ticketASurveiller', models.CharField(blank=True, max_length=100, verbose_name='Ticket a surveiller')),
                ('raisonDeSurveillance', models.CharField(blank=True, max_length=100, verbose_name='Raison de surveillance')),
                ('typeDeRequete', models.CharField(blank=True, max_length=100, verbose_name='Type de requete')),
                ('impact', models.CharField(blank=True, max_length=100, verbose_name='Impact')),
                ('urgence', models.CharField(blank=True, max_length=100, verbose_name='Urgence')),
                ('priorite', models.CharField(blank=True, max_length=100, verbose_name='Priorite')),
                ('equipe', models.CharField(blank=True, max_length=100, verbose_name='Equipe')),
                ('approbateur', models.CharField(blank=True, max_length=100, verbose_name='Approbateur')),
                ('dateDebut', models.DateField(blank=True, verbose_name='Date de debut')),
                ('derniereMiseAJour', models.DateTimeField(auto_now=True, verbose_name='Derniere mise a jour')),
                ('dateAssignation', models.DateField(blank=True, verbose_name="Date d'assignation")),
                ('echeanceTTR', models.DateField(blank=True, verbose_name='Echeance TTR')),
                ('requeteParente', models.CharField(blank=True, max_length=100, verbose_name='Requete parente')),
                ('changementParent', models.CharField(blank=True, max_length=100, verbose_name='Changement parent')),
                ('dureeDeResolution', models.CharField(blank=True, max_length=100, verbose_name='Duree de resolution')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('site_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticketmam.siteintervention', verbose_name='Site')),
            ],
        ),
    ]
