# Generated by Django 4.2.2 on 2023-08-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketmam', '0009_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, verbose_name='Nom')),
                ('adresse', models.CharField(blank=True, max_length=100, verbose_name='Adresse')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('telephone', models.CharField(blank=True, max_length=100, verbose_name='Telephone')),
                ('email', models.CharField(blank=True, max_length=100, verbose_name='Email')),
            ],
        ),
    ]
